/**
 * VANTAIR: THE COMPUTATIONAL SOFTWARE REALITY ENGINE
 * Epistemic Modal Logic & 6-Valued Truth Lattice
 *
 * Epistemic Classifications:
 * - OBSERVED: Ground truth directly witnessed in AST syntax or eBPF traces (kappa = 1.0)
 * - DERIVED: Formally proven via deterministic algorithms / SMT solvers (kappa = 1.0)
 * - INFERRED: High-probability consensus synthesized from documentation / comments (kappa = [0.75, 0.99))
 * - HYPOTHESIZED: Generated by Counterfactual Simulator awaiting verification (kappa = [0.50, 0.75))
 * - UNKNOWN: Execution branch with zero test / trace / doc coverage (kappa = 0.0) - Dark Matter
 * - CONTRADICTED: Mathematical contradiction where two layers assert mutually incompatible claims (kappa = -1.0)
 */

export enum EpistemicStatus {
  OBSERVED = "OBSERVED",
  DERIVED = "DERIVED",
  INFERRED = "INFERRED",
  HYPOTHESIZED = "HYPOTHESIZED",
  UNKNOWN = "UNKNOWN",
  CONTRADICTED = "CONTRADICTED",
}

export interface EpistemicValue {
  status: EpistemicStatus;
  certainty: number; // 0.0 to 1.0, or -1.0 for CONTRADICTED
  provenance: string; // Source layer or proof method
  evidenceCount: number;
  lastVerifiedAt: number; // epoch ms
}

/**
 * Priority order for Epistemic Truth Lattice:
 * CONTRADICTED > OBSERVED = DERIVED > INFERRED > HYPOTHESIZED > UNKNOWN
 */
export const EPISTEMIC_PRIORITY: Record<EpistemicStatus, number> = {
  [EpistemicStatus.CONTRADICTED]: 5,
  [EpistemicStatus.OBSERVED]: 4,
  [EpistemicStatus.DERIVED]: 4,
  [EpistemicStatus.INFERRED]: 3,
  [EpistemicStatus.HYPOTHESIZED]: 2,
  [EpistemicStatus.UNKNOWN]: 1,
};

export function createEpistemicValue(
  status: EpistemicStatus,
  provenance: string,
  certaintyOverride?: number,
  evidenceCount: number = 1
): EpistemicValue {
  let certainty = 1.0;
  switch (status) {
    case EpistemicStatus.OBSERVED:
    case EpistemicStatus.DERIVED:
      certainty = 1.0;
      break;
    case EpistemicStatus.INFERRED:
      certainty = 0.85;
      break;
    case EpistemicStatus.HYPOTHESIZED:
      certainty = 0.65;
      break;
    case EpistemicStatus.UNKNOWN:
      certainty = 0.0;
      break;
    case EpistemicStatus.CONTRADICTED:
      certainty = -1.0;
      break;
  }

  return {
    status,
    certainty: certaintyOverride !== undefined ? certaintyOverride : certainty,
    provenance,
    evidenceCount,
    lastVerifiedAt: Date.now(),
  };
}

/**
 * Epistemic Join (Lattice Supreme) - Combines evidence from two observations
 */
export function epistemicJoin(v1: EpistemicValue, v2: EpistemicValue): EpistemicValue {
  // If either is contradicted or if they contradict each other
  if (v1.status === EpistemicStatus.CONTRADICTED || v2.status === EpistemicStatus.CONTRADICTED) {
    return createEpistemicValue(
      EpistemicStatus.CONTRADICTED,
      `Join contradiction: [${v1.provenance}] vs [${v2.provenance}]`,
      -1.0,
      v1.evidenceCount + v2.evidenceCount
    );
  }

  const p1 = EPISTEMIC_PRIORITY[v1.status];
  const p2 = EPISTEMIC_PRIORITY[v2.status];

  const primary = p1 >= p2 ? v1 : v2;
  const secondary = p1 >= p2 ? v2 : v1;

  // Boost certainty slightly when multiple independent sources agree
  const combinedCertainty = Math.min(1.0, primary.certainty + secondary.certainty * 0.05);

  return {
    status: primary.status,
    certainty: primary.status === EpistemicStatus.OBSERVED || primary.status === EpistemicStatus.DERIVED ? 1.0 : combinedCertainty,
    provenance: `${v1.provenance} + ${v2.provenance}`,
    evidenceCount: v1.evidenceCount + v2.evidenceCount,
    lastVerifiedAt: Math.max(v1.lastVerifiedAt, v2.lastVerifiedAt),
  };
}
